// <auto-generated />
using System;
using CRUDApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUDApp.Migrations
{
    [DbContext(typeof(CrudDbContext))]
    [Migration("20201205182755_ADDResto")]
    partial class ADDResto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CRUDApp.Models.Personne", b =>
                {
                    b.Property<int?>("PersonneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodePostal")
                        .HasColumnType("int");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonneId");

                    b.ToTable("Personnes");

                    b.HasData(
                        new
                        {
                            PersonneId = 1,
                            Adresse = "Allée Reaumure",
                            CodePostal = 26000,
                            Mail = "dialloabdou26@gmail.com",
                            Nom = "DIALLO",
                            Prenom = "Abdou",
                            Telephone = "06 16 43 28 73",
                            Ville = "Valence"
                        },
                        new
                        {
                            PersonneId = 2,
                            Adresse = "5C Eugene Varlin",
                            CodePostal = 93000,
                            Mail = "barryami26@gmail.com",
                            Nom = "Barry",
                            Prenom = "Aminata",
                            Telephone = "06 13 43 75 83",
                            Ville = "Montreuil"
                        },
                        new
                        {
                            PersonneId = 3,
                            Adresse = "3 martin Guemou",
                            CodePostal = 13000,
                            Mail = "alybah26@gmail.com",
                            Nom = "Bah",
                            Prenom = "Aly",
                            Telephone = "06 13 66 75 23",
                            Ville = "Marseil"
                        },
                        new
                        {
                            PersonneId = 4,
                            Adresse = "13 allée clotures",
                            CodePostal = 33000,
                            Mail = "MSow26@gmail.com",
                            Nom = "Sow",
                            Prenom = "Moussa",
                            Telephone = "06 43 53 15 73",
                            Ville = "Grenoble"
                        },
                        new
                        {
                            PersonneId = 5,
                            Adresse = "13 allée des Martirs",
                            CodePostal = 73000,
                            Mail = "Mcamara26@gmail.com",
                            Nom = "Camara",
                            Prenom = "Amara",
                            Telephone = "06 43 15 15 73",
                            Ville = "Paris"
                        });
                });

            modelBuilder.Entity("CRUDApp.Models.Resto", b =>
                {
                    b.Property<int>("RestoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RestoId");

                    b.ToTable("Restos");
                });

            modelBuilder.Entity("CRUDApp.Models.Sondage", b =>
                {
                    b.Property<int>("SondageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("SondageId");

                    b.ToTable("Sondages");
                });

            modelBuilder.Entity("CRUDApp.Models.Vote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PersonneId")
                        .HasColumnType("int");

                    b.Property<int?>("RestoId")
                        .HasColumnType("int");

                    b.Property<int?>("SondageId")
                        .HasColumnType("int");

                    b.HasKey("VoteId");

                    b.HasIndex("PersonneId");

                    b.HasIndex("RestoId");

                    b.HasIndex("SondageId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("CRUDApp.Models.Vote", b =>
                {
                    b.HasOne("CRUDApp.Models.Personne", "Personne")
                        .WithMany()
                        .HasForeignKey("PersonneId");

                    b.HasOne("CRUDApp.Models.Resto", "Resto")
                        .WithMany()
                        .HasForeignKey("RestoId");

                    b.HasOne("CRUDApp.Models.Sondage", null)
                        .WithMany("Votes")
                        .HasForeignKey("SondageId");
                });
#pragma warning restore 612, 618
        }
    }
}
